---
title: "Graficos"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gráficos con la función `plot`


```{r primer_plot, fig.cap="Gráfico basico de uso del plot con alumnos y notas", fig.align='center'}
alumnos = c(1:10)
notas= c(2,5,7,9,3,5,6,10,7,6)

plot(alumnos,notas)
```

```{r}
plot(2^(1:6))
```

```{r}
f<- function(x){sqrt(x)}
plot(f)
```

## Gráficos  `fibonacci`
```{r}
n= 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n 
fib
plot(fib,xlab= "n", ylab=expression(f[n]),
      main= "Sucesión de Fibonacci", pch=20)
```


## Tipos de gráficos
```{r}
par(mfrow = c(3,2))
x = c(50:59)
y = c(9,2,25,3,100,77,62,54,19,40)
plot(x,y, pch = 20, cex = 2, col = "blue", type = "p")
plot(x,y, pch = 20, cex = 2, col = "blueviolet", type = "l")
plot(x,y, pch = 20, cex = 2, col = "gold", type = "b")
plot(x,y, pch = 20, cex = 2, col = "deeppink", type = "o")
plot(x,y, pch = 20, cex = 2, col = "springgreen", type = "h")
plot(x,y, pch = 20, cex = 2, col = "firebrick1", type = "s")
par(mfrow = c(1,1))

```

## Mas parametros de `plot`
```{r}
x = (2*(1:20))
y = (-1)^(1:20)*5*(1:20)
plot(x,y, main = "Ejemplo de grafico", pch = 8, cex = 1, type = "b", lty = 4, lwd = 4, xaxp = c(0,40,2), yaxp = c(-100,100,8))
```


