---
title: "Points y Text"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gr치ficos con la funci칩n `plot`
```{r}
x = (2*(1:20))
y = (-1)^(1:20)*5*(1:20)
plot(x,y, main= "Poniendo un punto en la recta", pch= 8, cex=1, type= "b", lty= 4, lwd= 4, xaxp = c(0,40,2), yaxp= c(-100,100,8))

points(20,0, col= "red", cex= 4, pch= 16)
abline(h= 0, lty= 2, col= "dodgerblue")##linea horizontal
```

##C칩mo a침adir elementos a un grafico
```{r}
f <- function(x){
  x^2 - 2*x + sqrt(abs(x))
}
plot(f, xlim = c(-3,3))
points(0,0, pch = 19)
points(-3:3, (-3:3)^2, col= "blue")
abline(2,3, lty= "dashed", col= "red")
abline(v=2, lty= "dotted", col= "green")
abline(h=5, lty= "dotdash", col= "gray")
```

```{r}
f<- function(x){x^2}
plot(f, xlim= c(-3,3), col= "red", lwd=2, ylab= expression(y^2), xlab= "x")
abline(h=0:9, v= -3:3, lty= "dotted", col= "gray")
```

##Uso de Text
```{r}
alumnos= c(1:10)
notas= c(2,5,7,9,8,3,5,6,10,7)
plot(alumnos,notas, main="Grafico con texto")
text(alumnos,notas, labels= c("S","A","N","F","N","S","A","A","E","N"), pos=(c(rep(3,times=8 ), 1,3)))
```

```{r}
plot(0,0)
text(0,0, labels="debajo", pos=1)
text(0,0, labels="izq", pos=2)
text(0,0, labels="arriba", pos=3)
text(0,0, labels="der", pos=4)
points(0,1)
text(0,1, labels="centro")
```

```{r}
f<- function(x){x^2}
plot(f, xlim=c(-3,3), ylim= c(-10,10))
points(-3:3, f(-3:3), pch= 19)
lines(-3:3, f(-3:3), lwd=2, lty= "dotted", col="red")
curve(x^3, lty= "dashed", col= "blue", add= TRUE)
curve(x^4, lty= "dashed", col="orangered", add=TRUE)
```

```{r}
x= c(5*(1:20))
plot(x,c(exp(-x)+(-1)^x*x/2*sin(x)^2))
lines(c(20,10,40,80,60,60,20), c(20,0,-20,-20,40,0,20), lwd=2, col= "darkslategray1")
curve(20*sin(x), add= TRUE, col= "green")
```


